version: 0.2
env:
  parameter-store:
    ALLOW_ORIGIN: "ALLOW_ORIGIN"
    API_PORT: "API_PORT"
    SPOTIFY_ENDPOINT: "SPOTIFY_ENDPOINT"
    SPOTIFY_ID: "SPOTIFY_ID"
    SPOTIFY_SECRET: "SPOTIFY_SECRET"
    SPOTIFY_BASIC_KEY: "SPOTIFY_BASIC_KEY"

  variables:
    IMAGE_NAME: "spotify_recommend_app"
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - export ALLOW_ORIGIN=${ALLOW_ORIGIN}
      - export API_PORT=${API_PORT}
      - export SPOTIFY_ENDPOINT=${SPOTIFY_ENDPOINT}
      - export SPOTIFY_ID=${SPOTIFY_ID}
      - export SPOTIFY_SECRET=${SPOTIFY_SECRET}
      - export SPOTIFY_BASIC_KEY=${SPOTIFY_BASIC_KEY}
      - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_NAME}
  build:
    commands:
      - docker build -t $URI:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker push $URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - printf '{"Version":"1.0","ImageURI":"%s"}' $URI:$CODEBUILD_RESOLVED_SOURCE_VERSION > imageDetail.json
artifacts:
  files: imageDetail.json
